name: RentMiro Monitor
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # Hourly

jobs:
  RunRentMiroMonitor:
    name: MonitorRentMiroData
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Python3 environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip3 install -r ./core/requirements.txt
      
      - name: Fetch rentmiro data
        run: bash ./modules/rentmiro/cronjob.sh
      
      - name: Commit files 
        id: commit-files
        run: |
          if [ -n "$(git status --porcelain modules/rentmiro/data.json modules/rentmiro/data.html)" ]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add modules/rentmiro/data.json modules/rentmiro/data.html
            git commit -m "action: update rentmiro data"
            echo "hasChange=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected in rentmiro data"
          fi
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ steps.commit-files.outputs.hasChange == 'true' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      
      - name: Send mail
        uses: dawidd6/action-send-mail@master
        if: ${{ steps.commit-files.outputs.hasChange == 'true' }}
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.QQEMAIL_USERNAME }}
          password: ${{ secrets.QQEMAIL_TOKEN }}
          subject: 'RentMiro Data Update Notification'
          html_body: file://modules/rentmiro/data.html
          to: ${{ secrets.QQEMAIL_RECIPIENTS }}
          from: GitHub Actions
